// ==UserScript==
// @name         Remove unwanted autogenerated lists
// @version      2025-07-02
// @description  Make youtube great again!
// @author       You
// @match        https://www.youtube.com/watch*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=youtube.com
// ==/UserScript==

// URL Parameter Detector - Checks for "list" parameter and offers removal

(function () {
    // Get current URL and parse parameters
    const currentUrl = new URL(window.location.href);
    const urlParams = new URLSearchParams(currentUrl.search);

    // Check if "list" parameter exists
    if (urlParams.has("list")) {
        const listValue = urlParams.get("list");

        // Ask user if they want to remove the "list" parameter
        const userResponse = confirm(`The URL contains a "list" parameter with value: "${listValue}"\n\nWould you like to remove this parameter from the URL?`);

        if (userResponse) {
            // Remove the "list" parameter
            urlParams.delete("list");

            // Construct new URL without the "list" parameter
            const newUrl = currentUrl.origin + currentUrl.pathname;
            const remainingParams = urlParams.toString();

            // Add remaining parameters if any exist
            const finalUrl = remainingParams ? `${newUrl}?${remainingParams}` : newUrl;

            // Reload the page with the new URL
            window.location = finalUrl;
        } else {
            console.log('❌ User chose to keep the "list" parameter');
        }
    } else {
        console.log('ℹ️ No "list" parameter found in URL');
    }
})();
